.\" Manpage for simple_shell.
.\" conctact Joseph Gleason and Kamila Sostre if any bugs occur
.TH "April 2025" "simple_shell man page"

.SH NAME
simple_shell - interface that is a command line interpreter

.SH SYPNOSIS
#include "shell.h"
./hsh

.SH DESCRIPTION
This Simple Shell is a custom made command line interpreter with an interface
thats works between the operating system and user. It uses the built-in functions
that were written into this program. To call this program write ./hsh in the terminal.

.SH SUPPORT
This program uses interactive and non-interactive modes,
only built-in functions can be used in this custom shell terminal.

.SH EXAMPLE

.TP
Interactive:
.nf
$ ./hsh
$ ls -l
$ exit
.fi

.TP
Non-Interactive:
.nf
$ echo "ls" | ./hsh
.fi

.SH FUNCTIONS
.TP
void display_prompt (void) - Used to print the shells prompt to stdout
.TP
char *find_command(char *command) - Looks for the full path of a command in the PATH to free
.TP
char **input_handler(char *line) - Analyzes and interprets syntax of a text to extract the arguments
.TP
int execute_shell(void) - Manages the PATH to execute the shell terminal
.TP
int second_handler(char **args) -  Checks if for the NULL line and prints the error message

.SH BUGS
There is no known bugs in this program.

.SH AUTHORS
[Joseph Gleason - https://github.com/JosephGleason]
[Kamila Sostre - https://github.com/kamisos3]
